### ISSUE TITLE
Parameterize Camunda/Tomcat port via env var

### ISSUE THREAD

**Issue by sergiojoker11** [camunda/docker-camunda-bpm-platform#108]
Sometimes from inside container one needs to hit some server running on localhost and 8080 is a very common port. Not always it is possible to change the other applications so my suggestion is to provide a way of selecting the port on which, at least, Tomcat runs.

**Comment by AndreaGiardini** [comment]
Hello @sergiojoker11 

Can you please describe better your use-case? Inside a container there should be only one process running (in this case the Camunda engine) so it's not clear to me why this is causing a conflict for you.

**Comment by varnem2** [comment]
Plus, that's part of Docker's thing.. Having the ability to switch ports. When you have your docker run command you can specify different ports. ex: `docker run -d --name camunda -p 8081:8080 camunda/camunda-bpm-platform:latest` to run on your local machine port 8081. See docker documentation https://docs.docker.com/v17.12/edge/engine/reference/commandline/run/#publish-or-expose-port--p-expose

**Comment by sergiojoker11** [comment]
Correct, one could definitely do that. However, the solutions you both are
proposing are suitable to connect to Camunda. What if from within Camunda
you have process instances that want to talk to other servers on localhost.
My use case is: in docker-compose there is a Camunda container (on port
8080, quite a common port to use, is it not?) and $otherService running on
localhost:8080. Then, a process instance that contains a task with a
http-connector sends a http request to $otherService. In order to achieve
this in docker-compose, we could set the 'network_mode: host'. At this
point, the port collision happens.
There might be other ways of achieving this but they all seem more
complicated than changing the port of Camunda.

**Comment by AndreaGiardini** [comment]
As @varnem2 explained, the power of Docker is that you don't have to rely on fixed ports. All the main java applications use port 8080 (e.g. Jenkins https://github.com/jenkinsci/docker/blob/master/README.md , Keycloack https://hub.docker.com/r/jboss/keycloak/ etc.) exactly for that reason: it's the default and it shouldn't matter.

While I understand that your setup doesn't work I am afraid your use-case is too unconventional to justify a change in our base image. I suggest you try to avoid `network_mode: host` and try to Dockerize all your other services otherwise, you are free to rebuild your own image using ours as base.

I am going to close this issue since it's not something that we are going to introduce

**Comment by sergiojoker11** [comment]
Fine.
For those that are still interested to change the port on docker-compose. There is a way.

1)Copy the /camunda/conf/server.xml next to your docker-compose.yml and change the ocurrences of 8080 to your desired choice. 
1.1)[Optional]Rename the file if you wish
2)In your docker-compose file mount the updated file replacing the original one like this:
```
services:
  camunda-engine:
    image: camunda/camunda-bpm-platform:tomcat-7.11.0
    restart: always
    network_mode: host
    volumes:
      - ${PWD}/camunda-server.xml:/camunda/conf/server.xml
```
Note: I renamed my server.xml to camunda-server.xml

**Comment by staylorx** [comment]
@sergiojoker11 ... sorry you were misunderstood on this. It would have been a helpful environment variable. Too bad.

**Comment by sergiojoker11** [comment]
No problem at all.
Finally, I worked around it by making a copy of camunda.xml (if I recall
correctly) and replacing it with a tweaked version where the port is
changed. Not ideal as every time a new version is released I need to make
sure my xml copy is up-to-date with the new one. So, it would still be
helpful if the post is changeable with a environment var.
