### ISSUE TITLE
can not run with a arbitrary user

### ISSUE THREAD

**Issue by nesies** [camunda/docker-camunda-bpm-platform#112]
The Dockerfile force the container to run as "camunda" user.

In Openshift, the user is randomized and the container is not run as "root"

**Comment by AndreaGiardini** [comment]
Hello @nessei 

I'm not sure I fully understand the issue. Can you please explain further what is the problem and what are you trying to achieve? Thanks

**Comment by nessei** [comment]
$ **oc debug pod/camunda-upstream**
Starting pod/camunda-upstream-debug ...
/camunda $ **id**
uid=1001900000(1001900000) **gid=0(root) groups=1001900000**
/camunda $ **./camunda.sh**
Configure database
failed to load external entity "/camunda/conf/server.xml"
./camunda.sh: line 30: Error: command not found

/camunda $ **ls -ln /camunda |grep conf**
d**rwx------**    2 1000     **1000**           262 Aug 14 21:19 conf
/camunda $ **cd /camunda/conf**
/bin/sh: cd: can't cd to /camunda/conf: Permission denied

/camunda/conf is owned by 1000.1000
uid of camunda is not 1000
uid 1001900000 is not part of group 1000

**Comment by koevskinikola** [comment]
Closing since this issue was superseded by #115, and that one was closed already.
