### ISSUE TITLE
Add MariaDB-support to docker image

### ISSUE THREAD

**Issue by ChrMaass** [camunda/docker-camunda-bpm-platform#116]
Hello guys. 

It would be grateful if you can integrate an MariaDB driver into the docker image.

Thanks a lot.

**Comment by AndreaGiardini** [comment]
Hello @ChrMaass :)

There are no plans on our site to integrate the MariaDB driver in the docker image, but we are willing to review contributions!

**Comment by mckenziec** [comment]
I second this. I came here looking for any notes on schema loading for a MariaDB setup.

**Comment by mckenziec** [comment]
Is it as simple as adding the MariaDB client connection jar to the docker image /camunda/libs folder, then setting the DB_URL to jdbc:mariadb://localhost:3306/camunda? https://downloads.mariadb.org/connector-java/

Also, what about DB schema loading? This project doesn't include the identity and engine schemas. Should I grab them from the official Camunda source and load them into the DB, or does the container do that automatically?

Thanks!

**Comment by AndreaGiardini** [comment]
Hello @mckenziec 

Yes, adding a new DB driver is as easy as that
Camunda BPM will load the initial (empty) schema in the DB, populating it with the right tables, you don't need to worry about that :)

**Comment by mckenziec** [comment]
FYI for anyone else wanting to make this cumunda docker image work with mariadb:

1. Camunda is missing the MariaDB jdbc driver, so we need to include it. Download: https://downloads.mariadb.org/connector-java/
2. Copy the jar to the camunda docker root directory.
3. Add "COPY ./mariadb-java-client-2.5.4.jar /camunda/lib" to the end of the Camunda Dockerfile
4. Docker build it.

In your docker-compose.yml or docker run, make sure to set the DB envs accordingly:

DB_DRIVER=org.mariadb.jdbc.Driver
DB_URL=jdbc:mariadb://database:3306/camunda
DB_USERNAME=camunda
DB_PASSWORD=camundadbpass
WAIT_FOR=db:3306

What I did in my docker-compose.yml is link the db as "database" then the DB_URL can point to the "database" hostname.

services:
  bpm:
    image: camunda/camunda-bpm-platform:latest
    container_name: bpm
    ports:
      - "8009:8009"
      - "8080:8080"
    env_file:
      - ${PWD}/.env <- this is where I put the DB variables above
    links:
      - "db:database"

Finally, although camunda can now try to reach the db, and it will load its schema, it won't create the db itself for you. With the official mariadb image, from the mariadb people, you can volume mount /docker-entrypoint-initdb.d/ and any .sql or .sh files in there will be run when booting the container.

  db:
    image: mariadb/server:10.4
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - ${PWD}/.env
    volumes:
      - ${PWD}/db:/var/lib/mysql
      - ${PWD}/init_db:/docker-entrypoint-initdb.d

So for camunda you'll want to create the db, add a user and grant them remote access (local is not enough):

CREATE USER 'camunda'@'localhost' IDENTIFIED BY 'p2FGR0gze5Kh';
CREATE USER 'camunda'@'%' IDENTIFIED BY 'p2FGR0gze5Kh';
create database camunda;
GRANT ALL PRIVILEGES ON camunda.* to 'camunda'@'localhost';
GRANT ALL PRIVILEGES ON camunda.* to 'camunda'@'%';

My sql might be clumbsy as it will try creating the table everytime. It would be great if the sql only ran once. It'll be run everytime the container is started, so be careful not to drop, then create. It might need a script to run before the sql, to block the sql if the db already exists.

Good luck!

**Comment by koevskinikola** [comment]
Hi @mckenziec and @ChrMaass,

I am closing this ticket, as it seems that the issue was resolved since you can extend the Camunda Docker image.

Furthermore, the Camunda Docker image provides the MySQL JDBC driver, which is compatible with MariaDB.

**Note:** We will soon disable the GitHub issues on this repository.

If you still think that we should add MariaDB support to the Camunda Docker image, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) and create a CAM ticket there.

Best,
Nikola
