### ISSUE TITLE
Add DB2 support

### ISSUE THREAD

**Issue by viloskovic** [camunda/docker-camunda-bpm-platform#121]
Hi

Will there be DB2 support in one of the upcoming releases?

Kind regards
Ruben

**Comment by AndreaGiardini** [comment]
Hello @viloskovic 

The current image is provided mainly for quick start. If you need additional drivers you can create your own image and use this one in the `FROM` directive of your Dockerfile.
I am not sure if including DB2 drivers inside our Docker image is ok from the licensing point of view.

**Comment by viloskovic** [comment]
You are probably right from the licensing point. Currently I am indeed using this image as base image for my docker image. Thanks.

**Comment by AndreaGiardini** [comment]
I am closing this issue since we probably won't include the DB2 drivers in the Docker image
