### ISSUE TITLE
container starts with a default user with a default password

### ISSUE THREAD

**Issue by nesies** [camunda/docker-camunda-bpm-platform#122]
I should be convenient (and more secure) to let user to choose a default "admin" user
environment variables ?
config file via a volume ?

**Comment by lwille** [comment]
Default credentials present
only when starting
with an empty database -
`SKIP_DB_CONFIG`,
to enforce set-up by hand,
as environment.

For similar questions please
check out our forum
at forum.camunda.org

**Comment by nesies** [comment]
yes, i am starting from a empty database.

If i set SKIP_DB_CONFIG, Camunda will not work, /conf/server.xml will have to DB url/username/password

**Comment by lwille** [comment]
In this case, please mount your configuration file into the container.

Please refer to our [forum](https://forum.camunda.org) for further configuration questions.
