### ISSUE TITLE
Camunda Nexus repository url not working..

### ISSUE THREAD

**Issue by pradyunvalluri** [camunda/docker-camunda-bpm-platform#124]
Hi 

I am creating the camunda CE docker image specific to centos7 . 
I am following https://github.com/camunda/docker-camunda-bpm-platform github aritical for the same.
In the docker file , I am using "https://github.com/camunda/docker-camunda-bpm-platform/blob/next/download.sh" to down load the CE edition of camunda .

However it looks like nexus repository url in the download.sh seems to be not working.

Seeing the below error when building the image.

can you pls verify and let me know if the issue with nexus repository url or something else is causing the error below?

Let me know if you need any other details from my end.

Regards
Prabhu
----------------------------------------------------------------------
Error:
Downloaded: https://repo.maven.apache.org/maven2/velocity/velocity-dep/1.4/velocity-dep-1.4.jar (506 KB at 263.2 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.763s
[INFO] Finished at: Thu Feb 13 08:34:20 UTC 2020
[INFO] Final Memory: 10M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.1:get (default-cli) on project standalone-pom: The parameters 'repositoryUrl' for goal org.apache.maven.plugins:maven-dependency-plugin:2.1:get are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
The command '/bin/sh -c /tmp/download.sh' returned a non-zero code: 1
---------------------------------

**Comment by AndreaGiardini** [comment]
Hello @pradyunvalluri 

Can you post your Dockerfile and/or Docker command?
Without this information it is difficult to help you.

**Comment by ingorichtsmeier** [comment]
Hi @pradyunvalluri ,

I can download the jar behind the URL on my laptop. I think, on your site it's a network or proxy issue.

Hope this helps, Ingo

**Comment by pradyunvalluri** [comment]
Hi 

Thanks for the reply..
I am attaching the docker file and error screen prints.
Building of docker image fails at the point "RUN /tmp/download.sh."
when I browse the nexus repository url below "**https://app.camunda.com/nexus/content/repositories/camunda-bpm**" **i see 404 error**.

![Url](https://user-images.githubusercontent.com/43677309/74451441-ecdde680-4e7f-11ea-8fbe-52962caa35b0.PNG)
![error](https://user-images.githubusercontent.com/43677309/74451444-ed767d00-4e7f-11ea-986d-002aee2d44e2.PNG)

[Dockerfile.txt](https://github.com/camunda/docker-camunda-bpm-platform/files/4199139/Dockerfile.txt)

Help to solve the issue. let me know if you need any other details from my end.

Regards
Prabhu

**Comment by AndreaGiardini** [comment]
Running this command in the repo builds the image correctly (as written in the README):
```
➜ docker build -t camunda-bpm-platform \                                                                                                                                                                             --build-arg DISTRO=tomcat \            
  --build-arg VERSION=7.13.0 \    
  --build-arg SNAPSHOT=true .  
```

But your Dockerfile doesn't seem to work. Maybe some shell variable is not escaped correctly?

**Comment by pradyunvalluri** [comment]
Hi

Thanks for the reply..

I am not facing the issue at the docker build..i am facing the issue at "RUN /tmp/download.sh." in the docker file..

i.e., the download.sh is unable to download from the repository.. 
to be more clear the below piece of the script in the download.sh is failing with error i reported.

"mvn dependency:get -B --global-settings /tmp/settings.xml \
    $PROXY \
    -**DremoteRepositories="camunda-nexus::::https://app.camunda.com/nexus/content/repositories/${REPO}" \**
    -DgroupId="${ARTIFACT_GROUP}" -DartifactId="${ARTIFACT}" \
    -Dversion="${ARTIFACT_VERSION}" -Dpackaging="tar.gz" -Dtransitive=false
cambpm_distro_file=$(find /m2-repository -name "${ARTIFACT}-${ARTIFACT_VERSION}.tar.gz" -print | head -n 1)"

**Comment by pradyunvalluri** [comment]
Hi AndreaGiardini

Thanks again for the reply...

I verified today with your Docker file , it works perfectly fine. i,e alpine based.

However this is failing when creating the centos based .

did you set any thing specific to maven on alpine base image? 

I want to create the camunda image with centos as base..

please advise.

Regards
Prabhu

**Comment by AndreaGiardini** [comment]
Hello @pradyunvalluri 

The build error seems to be related to the centos base (maybe shell escaping?).
Our docker image and nexus repository work correctly, as you confirmed in your previous post. For this reason, I will mark this issue as closed.

If you want to get additional support from our community I recommend that you open a new thread in our forum https://forum.camunda.org/ :)
