### ISSUE TITLE
Error querying database.  Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit

### ISSUE THREAD

**Issue by mckenziec** [camunda/docker-camunda-bpm-platform#125]
Hi.

I'm trying to use MariaDB (by including the MariaDB client jar, and setting the jdbc url accordingly) and its been good but after awhile my Camunda docker container throws this:

```
16-Feb-2020 20:54:30.059 SEVERE [Thread-5] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: 
### Error querying database.  Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLNonTransientConnectionException: (conn=18) Connection is closed
### The error may exist in org/camunda/bpm/engine/impl/mapping/entity/Job.xml
### The error may involve org.camunda.bpm.engine.impl.persistence.entity.JobEntity.selectNextJobsToExecute
### The error occurred while executing a query
### Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLNonTransientConnectionException: (conn=18) Connection is closed
```

```
	Caused by: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLNonTransientConnectionException: (conn=195) Connection reset by peer (Write failed)
		at org.apache.ibatis.transaction.jdbc.JdbcTransaction.setDesiredAutoCommit(JdbcTransaction.java:107)
		at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:142)
		at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:60)
		at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
		at org.apache.ibatis.executor.BatchExecutor.doQuery(BatchExecutor.java:89)
```

In my /etc/mysql/mariadb.conf.d/my.cnf I've tried setting:
```
[mysqld]
transaction-isolation = READ-COMMITTED
```
I've also set my DB_URL to: jdbc:mariadb://database:3306/camunda?autoReconnect=true

No luck. After 15 minutes or so the exceptions start. Any clues??? Thanks.

**Comment by yanavasileva** [comment]
Hi @mckenziec,

This seems like a configuration issue that isn't related to the docker.
Could you please raise such questions in the [forum](https://forum.camunda.org) where you can find already some helpful posts or create a new one.
Have a look at this post that might help you to adjust your configuration:
https://forum.camunda.org/t/why-tomcat-need-to-restart-every-day/1173/3

Best regards,
Yana

**Comment by AndreaGiardini** [comment]
I will close this issue since it is not related with the Docker image

**Comment by mckenziec** [comment]
I'm using your Docker container. If I have to work out a fix by tuning the Tomcat you include, it feels like its a container issue, not a 3rd party J2EE server since you're included it.

**Comment by romansmirnov** [comment]
@mckenziec,

Can you please set the variable `DB_VALIDATE_ON_BORROW ` to `true`. This will make sure that a connection is validated before usage. For further details, please have a look at the README: https://github.com/camunda/docker-camunda-bpm-platform#database-environment-variables

In general and independent in which component the issues occur, we recommend raising such questions in the Camunda forum: https://forum.camunda.org/

I hope this helps to resolve the issue.

Best,
Roman
