### ISSUE TITLE
Switch base image from alpine

### ISSUE THREAD

**Issue by ceefour** [camunda/docker-camunda-bpm-platform#138]
https://github.com/camunda/docker-camunda-bpm-platform/blob/1f78b498716a34659e1c3d3af82e4fe52b700013/Dockerfile#L33

There have been a lot of discussions why `alpine` is no longer a preferred base image today:

* https://dev.to/asyazwan/moving-away-from-alpine-30n4
* https://pythonspeed.com/articles/base-image-python-docker-images/
* https://www.flownative.com/en/blog/choosing-a-secure-docker-base-image.html

### Alpine Cons

* rather poor documentation
* small team: currently there are 3 developers listed as the Alpine Linux team
* possible incompatibilities: musl libc may cause problems with some C-based plugins and adjustments may be necessary if you compile software yourself

### Ubuntu (or Debian) Pros

* small images (Canonical has interest in this)
   * `apt-get install --no-install-recommends` [gives ~60% reduction in image size](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends)
* lots of packages: there's hardly any software for Linux which hasn't been packaged for Debian
* well tested: due to its popularity, Debian is used widely and issues are more likely to be found
comprehensive documentation; also, the community produced a big amount of additional documentations and tutorials
* more security reviews: again, due to its larger community, Debian gets more attention and its more likely that vulnerabilities are discovered, e.g in glibc versus in musl libc (assumption). Debian also has a security audit team, which proactively looks for security issues.
* provenance: validating authenticity of packages is possible, e.g. with debsigs / dpkgsig

For myself (and I believe for most people), using Ubuntu or Debian base image is also making it easier to customize/manage/build on top of Camunda official docker images.

I propose to switch the base image to [`ubuntu:focal`](https://hub.docker.com/_/ubuntu/).
As an alternative, `debian:buster-slim` is also good for me.

**Comment by MrRickwi** [comment]
I also would love to see another base image. We like to use kerberos in the image, and alpine 3.12 has no support for kstart, alpine 3.13 has, but debian:buser-slim would be my favorite

**Comment by koevskinikola** [comment]
Hi everyone,

Thank you for raising this topic. Since we will soon disable the GitHub issues on this repository, I will close this ticket. Please follow [CAM-12893](https://jira.camunda.com/browse/CAM-12893) to track the progress of this FR.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
