### ISSUE TITLE
Username and password default does not working

### ISSUE THREAD

**Issue by santanarscs** [camunda/docker-camunda-bpm-platform#148]
Hi, after install camunda with docker, username and password default does not working

![Captura de tela de 2020-08-22 15-15-22](https://user-images.githubusercontent.com/8572296/90963581-1a3ec900-e48f-11ea-8193-28f1abf344ac.png)

**Comment by dondragon2** [comment]
I get the same issue when when running this on Kubernetes and have 3 pods running based on this tutorial.
[https://camunda.com/blog/2021/08/releasing-camunda-platform-community-helm-chart/](https://camunda.com/blog/2021/08/releasing-camunda-platform-community-helm-chart/)

There are no errors in the logs and all pods are running successfully. I am using PostgreSQL 13 running in the cluster
