### ISSUE TITLE
PostgreSQL driver does not support SCRAM authentication

### ISSUE THREAD

**Issue by juergenthomann** [camunda/docker-camunda-bpm-platform#149]
Hi,

The currently used PostgreSQL JDBC driver is quite old and does not support SCRAM. The lowest Version that supports it is 42.2.0.

I can create a PR, but I would like to know how it should be handled. Easiest would be to specify a fixed version in download.sh, but I would implement other ways as well if you prefer them. 

Thanks,
Jürgen

**Comment by AndreaGiardini** [comment]
Hi @juergenthomann 

Please have a look at https://github.com/camunda/docker-camunda-bpm-platform/issues/145 since it's directly related to your problem

**Comment by juergenthomann** [comment]
Hi @AndreaGiardini,

Thanks for the hint to that issue.

I found a ticket (https://jira.camunda.com/browse/CAM-12204) which is related to the old driver and it mentions that is intentionally to test that Camunda is compatible with the oldest supported version. As that is an understandable reason to keep it at that version I'll try to build my own image with a newer version.

**Comment by MaximMonin** [comment]
jiust download latest driver and mount like this
    volumes:
      - ./cfg/postgresql-42.2.18.jar:/camunda/lib/postgresql-9.4.1212.jar

**Comment by dondragon2** [comment]
@MaximMonin where you able to solve this on k8s? Especially one deployed on a cloud provider?

**Comment by MaximMonin** [comment]
> @MaximMonin where you able to solve this on k8s? Especially one deployed on a cloud provider?

I dont use k8s right now, but use Dockerfile and my own image with COPY jar statement, as far as i know k8s can work with custom image w/o mounting volumes

**Comment by koevskinikola** [comment]
With [CAM-14023](https://jira.camunda.com/browse/CAM-14023) we bumped the PostgreSQL JDBC driver version to `42.3.3`, so I am closing this issue.

Cheers,
Nikola
