### ISSUE TITLE
Latest Docker image has cock pit broken

### ISSUE THREAD

**Issue by dharmendrak** [camunda/docker-camunda-bpm-platform#150]
sha256:d0960e690425c4e30a3587cd676680ffeef2098f6f55203e0254ec24e332053b   9a4fa40a7a83 docker image issed 20 hours ago has cockpit broken

**Comment by GuSuku** [comment]
and this as well: sha256:07abe27839b00d3862db8ea7be2ea6193c7555219ac2e07ddd17ae92b0d64e5c

**Comment by AndreaGiardini** [comment]
Hi everyone

We are aware of the issue. Currently, the images published with the `latest` tag are basically SNAPSHOT images.
I would suggest to avoid using latest and rely on fixed tags like `7.13.0` for now

**Comment by yanavasileva** [comment]
The issue has been resolved with [CAM-12313](https://jira.camunda.com/browse/CAM-12313).
