### ISSUE TITLE
Documentation to setup CORS for wildfly-7.13.0

### ISSUE THREAD

**Issue by johnjacobkenny** [camunda/docker-camunda-bpm-platform#151]
I am using the docker image `camunda/camunda-bpm-platform:wildfly-7.13.0`. Is there any documentation on how to setup CORS policy? I saw #42 but I'm not getting that file structure in my docker container, and I'm thinking maybe the structure has changed.

Am I missing something?

**Comment by AndreaGiardini** [comment]
Hi @johnjacobkenny 
Did you try to have a look at our forum? https://forum.camunda.org/t/enable-cors-on-wildfly/673
Your question seems very wildfly-specific

**Comment by johnjacobkenny** [comment]
Hi @AndreaGiardini 
Thanks for the quick response.

I looked at both the links. I am not very familiar with wildfly config, but in order to make the change, I first need to know which xml file in the docker image needs to be modified. I did a find in the container and I got this as the path to the `standalone.xml` file. Is this the file I need to modify?

![image](https://user-images.githubusercontent.com/19240564/93969014-8495a280-fd88-11ea-9a3d-4e5c9a66d6ec.png)

**Comment by johnjacobkenny** [comment]
Unfortunately, I was not able to make much progress on the wildfly side. I'm not from a java background, and after a bit of digging, I understood that I need to change some of the configuration in the same file `standalone/configuration/standalone.xml`, but I didn't have much luck with it further.

For the time being I decided to go with a reverse proxy just for CORS called https://drishtilabs.github.io/cors-backdoor/. It's a quick and dirty way to get the job done for development purpose only.

**Comment by koevskinikola** [comment]
Hi @johnjacobkenny,

This seems to be a help request for configuring the Camunda Wildfly distro, and it's not strictly related to the Camunda Docker image. Therefore, I am closing this issue.

We will soon disable the GitHub issues on this repository.

For help requests, I would recommend opening a help request topic on the [Camunda forum](https://forum.camunda.org/) or [opening a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
