### ISSUE TITLE
Hardware requirements for running the docker-image?

### ISSUE THREAD

**Issue by cschaf** [camunda/docker-camunda-bpm-platform#153]
Hello Camunda Team,

what are the minimal hardware requirements for running the docker-camunda-bpm-platform?
I would like to test it on a virtual machine with debian.

Greetings
Christian

**Comment by koevskinikola** [comment]
Hi @cschaf,

Maybe this will help you: https://forum.camunda.org/t/minimum-hardware-for-camunda-to-support-50-users/810/2?u=nikola.koevski

I am closing this ticket. We will soon disable the GitHub issues on this repository,

For help requests, I would recommend opening a help request topic on the [Camunda forum](https://forum.camunda.org/) or [opening a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
