### ISSUE TITLE
Allow to remove examples without using volumes

### ISSUE THREAD

**Issue by menski** [camunda/docker-camunda-bpm-platform#16]
Something like an environment variable or file trigger should be available

**Comment by varnem2** [comment]
You could just add to the Dockerfile

```(Dockerfile)
FROM camunda/camunda-bpm-platform
RUN rm -r webapps/camunda-invoice
```

Or maybe using the

ONBUILD arg? 

What do you think?

**Comment by koevskinikola** [comment]
Hi everyone,

We will soon disable the GitHub issues on this repository. As a result, I am closing this issue. I created https://jira.camunda.com/browse/CAM-14451 in our issue tracker. You can follow the JIRA CAM ticket for updates.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
