### ISSUE TITLE
Run Distribution: Provide ability to limit the file sizes of deployments based on file extentions

### ISSUE THREAD

**Issue by StephenOTT** [camunda/docker-camunda-bpm-platform#161]
helping to remove issues where excessively large BPMNs are deployed.

**Comment by koevskinikola** [comment]
Hi @StephenOTT,

We don't watch the GitHub issues on this repository actively and plan to disable them soon.

Is there any reason why you didn't create a JIRA CAM ticket for this feature request?

Best,
Nikola

**Comment by koevskinikola** [comment]
Hi @StephenOTT,

I'm closing this issue. We already provide https://docs.camunda.org/javadoc/camunda-bpm-platform/7.16/org/camunda/bpm/engine/repository/DeploymentHandler.html, which is an interface that users can implement to modify how resource deployments are made.

**Note:**

We will soon disable the GitHub issues on this repository.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
