### ISSUE TITLE
Camunda Docker Cluster Issue

### ISSUE THREAD

**Issue by Manojkala** [camunda/docker-camunda-bpm-platform#162]
Working Scenario :
I have deployed camunda/camunda-bpm-platform:tomcat-7.15.0-SNAPSHOT into AWS ECS Fargate Cluster with One node and a Mysql DB. Everything is working fine.

Issue: 

If I add a new node to the cluster pointing to same above mysql Db, ending up with below error while logging in, If I remove the node and keep it as single node it is working fine again.

Login Failed :
Wrong credentials, locked user or missing access rights to application

Logs:

2021-01-07T12:08:35.238-06:00Copy07-Jan-2021 18:08:35.236 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002200: Adding class resource org.camunda.bpm.admin.impl.plugin.resources.BaseRootResource from Application class org.camunda.bpm.admin.impl.web.AdminApplication | 07-Jan-2021 18:08:35.236 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002200: Adding class resource org.camunda.bpm.admin.impl.plugin.resources.BaseRootResource from Application class org.camunda.bpm.admin.impl.web.AdminApplication
-- | --
  | 2021-01-07T12:08:35.238-06:00 | 07-Jan-2021 18:08:35.238 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002205: Adding provider class com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider from Application class org.camunda.bpm.admin.impl.web.AdminApplication
  | 2021-01-07T12:08:35.239-06:00 | 07-Jan-2021 18:08:35.238 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002200: Adding class resource org.camunda.bpm.admin.impl.web.SetupResource from Application class org.camunda.bpm.admin.impl.web.AdminApplication
  | 2021-01-07T12:08:35.239-06:00 | 07-Jan-2021 18:08:35.239 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.exception.ExceptionHandler from Application class org.camunda.bpm.admin.impl.web.AdminApplication
  | 2021-01-07T12:08:35.239-06:00 | 07-Jan-2021 18:08:35.239 INFO [http-nio-8080-exec-5] org.jboss.resteasy.spi.ResteasyDeployment.processApplication RESTEASY002205: Adding provider class org.camunda

**Comment by ingorichtsmeier** [comment]
Hi @Manojkala,

if you run Camunda BPM PLatform in a clustered environment, you have to configure your load balancer to use sticky sessions. Have a look at the docs for further details: https://docs.camunda.org/manual/7.14/introduction/architecture/#session-state-in-a-clustered-environment.

Hope this helps, Ingo
