### ISSUE TITLE
service task http connector in docker failing to deploy

### ISSUE THREAD

**Issue by bikashkarmakar** [camunda/docker-camunda-bpm-platform#171]
We are using the Camunda modeler 4.6.0 (4.6.0.7236) and are trying to deploy the model with a service task configured with Connector = "http-connector" to the docker instance with "camunda/camunda-bpm-platform:run-latest" .

We get the below error -
ENGINE-09005 Could not parse BPMN process. Errors: 
* One of the attributes 'class', 'delegateExpression', 'type', or 'expression' is mandatory on serviceTask. 

As per https://github.com/camunda/camunda-bpm-examples/tree/master/servicetask/rest-service , do we need to have Connect and Spin are optional extensions on the docker instance ?
Any pointer will be greatly appreciated?

**Comment by EdwinKuo** [comment]
I also encountered the same problem.
Only in "run" distribution, not in "tomcat".

**Comment by tillias** [comment]
How to manually mount those plugins? I have exactly the same issue with docker

**Comment by koevskinikola** [comment]
Ho @bikashkarmakar,

The Camunda Connect process engine plugin wasn't provided by default in the Camunda Run distribution. However, it is included in the Camunda Run distribution by default starting with version 7.17.0.

This will resolve your problem. Therefore, I am closing this ticket.

Note: We will soon disable the GitHub issues on this repository.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

For help requests, I please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

Best,
Nikola
