### ISSUE TITLE
supported Postgres version

### ISSUE THREAD

**Issue by dberardo-com** [camunda/docker-camunda-bpm-platform#174]
Hello,

which version of Postgres does the latest docker distribution currently support?

**Comment by ThorbenLindhauer** [comment]
Hi @dberardo-com,

PostgreSQL 9.4 / 9.6 / 10 / 11 / 12 (see https://docs.camunda.org/manual/7.14/introduction/supported-environments/#supported-database-products).

Cheers,
Thorben
