### ISSUE TITLE
camunda-run: Make Prometheus available

### ISSUE THREAD

**Issue by adrianschneider94** [camunda/docker-camunda-bpm-platform#175]
Monitoring is particularly in production environments important. So I think including the exporter in the run-distro is important.

**Comment by koevskinikola** [comment]
Hi @adrianschneider94,

I am closing this ticket in favor of https://jira.camunda.com/browse/CAM-14158. You can follow the progress on our JIRA issue tracker. Camunda Run is based on our Spring Boot Starter, so by adding support for Prometheus there, we will also provide it for Run.

**Note:**

We will soon disable the GitHub issues on this repository.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
