### ISSUE TITLE
Enabling JMX_PROMETHEUS overrides CATALINA_OPTS

### ISSUE THREAD

**Issue by sergiojoker11** [camunda/docker-camunda-bpm-platform#180]
The image has as a entry point the execution of `/camunda/camunda.sh` which configure the JMX exporter using the following snippet:
```
if [ "$JMX_PROMETHEUS" = "true" ] ; then
  echo "Enabling Prometheus JMX Exporter on port ${JMX_PROMETHEUS_PORT}"
  [ ! -f "$JMX_PROMETHEUS_CONF" ] && touch "$JMX_PROMETHEUS_CONF"
  export CATALINA_OPTS="-javaagent:/camunda/javaagent/jmx_prometheus_javaagent.jar=${JMX_PROMETHEUS_PORT}:${JMX_PROMETHEUS_CONF}"
fi
```
Obvs, that overrides whatever you had in $CATALINA_OPTS.

Since the users of this repo don't have access to `camunda.sh` I am raising the issue here until somebody points me at the right location.

**Comment by michals96** [comment]
Bumping this thread up, since this issue is popular in community.

https://forum.camunda.org/t/camundas-run-distribution-with-jmx-prometheus-configuration/33380

**Comment by koevskinikola** [comment]
Hi @sergiojoker11,

Thank you for reporting this. I confirmed the bug and created a ticket in our JIRA issue tracker: https://jira.camunda.com/browse/CAM-14448. You can follow it for updates, as well as contribute any additional hints there.

@michals96, the Camunda Forum thread you are referencing is related to Prometheus support for Camunda Platform Run. You can also check out #175.  A JIRA ticket already exists for this topic: https://jira.camunda.com/browse/CAM-14158. You can follow it for any updates.

**Note:** We will soon disable the GitHub issues on this repository.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
