### ISSUE TITLE
problem with java delegate

### ISSUE THREAD

**Issue by gabylan12** [camunda/docker-camunda-bpm-platform#183]
Hello!, i want to add a java delegate.
I try to deploy this example into the container https://docs.camunda.org/get-started/java-process-app/service-task/.

**docker-compose**
camunda:
    image: camunda/camunda-bpm-platform:run-7.15.0
    container_name: camunda
    environment:
      - TZ=America/Montevideo
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db_camunda:5432/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=db_camunda:5432
    ports:
      - "8080:8080"
    volumes:
      - "./camunda/publicarCatalogo.bpmn:/camunda/configuration/resources/publicarCatalogo.bpmn"
      - "./camunda/loan-approval-0.1.0-SNAPSHOT.war:/camunda/webapps/loan-approval-0.1.0-SNAPSHOT.war

**task**

`    <bpmn:serviceTask id="Activity_1kqlhqk" name="Noticia de catalogo nuevo" camunda:class="org.camunda.bpm.getstarted.loanapproval.ProcessRequestDelegate">
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="method">GET</camunda:inputParameter>
          <camunda:inputParameter name="Accept">application/json</camunda:inputParameter>
        </camunda:inputOutput>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_139gqs9</bpmn:incoming>
      <bpmn:outgoing>Flow_1huu23o</bpmn:outgoing>
    </bpmn:serviceTask>`

**But i have this exception** 

`Caused by: java.lang.ClassNotFoundException: org.camunda.bpm.getstarted.loanapproval.ProcessRequestDelegate
camunda       |         at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:72) ~[spring-boot-2.4.3.jar!/:2.4.3]`

This is the correct way to add my custom java class?

**Comment by koevskinikola** [comment]
Hi @gabylan12,

I am closing this issue, as we will soon disable the GitHub issues on this repository.

For help requests, I would recommend opening a help request topic on the [Camunda forum](https://forum.camunda.org/) or [opening a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
