### ISSUE TITLE
Unable to run docker container from instructions in README

### ISSUE THREAD

**Issue by amthorn** [camunda/docker-camunda-bpm-platform#185]
I'm unable to run the instructions from the readme in this repo. The container successfully starts but then errors and crashes (Logs below).

Commands i ran (Copied directly from the README)

```
docker pull camunda/camunda-bpm-platform:latest
docker run -d --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest
```

[logs.txt](https://github.com/camunda/docker-camunda-bpm-platform/files/6635341/logs.txt)

docker version:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I am using MacOS running Catalina version 10.15.7

**Comment by koevskinikola** [comment]
Hi @amthorn,

We will soon disable the GitHub issues on this repository. Therefore, I am closing this help request.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

I would recommend continuing the discussion on the forum where you can benefit from the knowledge of the wider Camunda community. The GitHub issues on this repository are not actively watched.

Best,
Nikola
