### ISSUE TITLE
Documentation how to use camunda-connect-connectors-all

### ISSUE THREAD

**Issue by tillias** [camunda/docker-camunda-bpm-platform#187]
Please provide documentation how to use connectors when starting camunda using docker:
https://docs.camunda.org/manual/7.15/user-guide/process-engine/connectors/

There is suggestion in https://github.com/camunda/docker-camunda-bpm-platform/issues/171 but it is not clear how to implement it

**Comment by EdwinKuo** [comment]
Use docker volumes, like:
```
docker run \
-p 8080:8080 \
-v ${PWD}/camunda-engine-plugin-connect-7.15.0.jar:/camunda/configuration/userlib/camunda-engine-plugin-connect-7.15.0.jar \
camunda/camunda-bpm-platform:run-7.15.0
```

**Comment by royyan-kargo** [comment]
> Use docker volumes, like:
> 
> ```
> docker run \
> -p 8080:8080 \
> -v ${PWD}/camunda-engine-plugin-connect-7.15.0.jar:/camunda/configuration/userlib/camunda-engine-plugin-connect-7.15.0.jar \
> camunda/camunda-bpm-platform:run-7.15.0
> ```

Thanks, this solved my issue

**Comment by koevskinikola** [comment]
Hi @tillias,

As of Camunda Platform 7.17.0, the Camunda Connect process engine plugin will be available out-of-the-box with Camunda Run.

Best,
Nikola
