### ISSUE TITLE
ppc64le support

### ISSUE THREAD

**Issue by vgrusdev** [camunda/docker-camunda-bpm-platform#189]
Hi!
I was able to build the docker image for ppc64le platform on the request of my colleagues.
It was easy, and run smoothly, just used your "docker build.."  command described in the README.
As the code is mostly java based.

I have easy access to the ppc64le platform and can build and verify images.
Do you think to add ppc64le images to the dockerhub ?

thanks, Valery.

**Comment by koevskinikola** [comment]
Hi @vgrusdev,

Thank you for raising this topic. Unfortunately, we will not add support for `ppc64le` Docker images. We don't have access to a `ppc64le` platform, so we can't guarantee the validity of those Docker images.

**Note:** We will soon disable the GitHub issues on this repository.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

Best,
Nikola
