### ISSUE TITLE
Provide Blueprints for Camunda BPM EE Docker Images

### ISSUE THREAD

**Issue by menski** [camunda/docker-camunda-bpm-platform#19]
An employee or customer should be able to use the blueprints to build its own EE docker image image

**Comment by z0rbas** [comment]
I have been searching for docker Camunda EE Wildfly images. It would be great to have those too.

**Comment by menski** [comment]
Please note that these images will only be available as Dockerfile and not on Docker Hub as you have to be an EE Customer to have access to the artifacts.

Btw I'm working on a rewrite of the docker images based on alpine linux. See https://github.com/menski/docker-camunda-bpm-platform. In this repo you can already build EE images using `./scripts/build-ee-images.sh USERNAME PASSWORD SERVER`. Where username and password are the Camunda nexus credentials and server the application server you want to build.

**Comment by z0rbas** [comment]
Thanks! I'll give your scripts a try.

**Comment by z0rbas** [comment]
The image builds after changing the repo from "private" to "camunda-bpm-ee". Most users probably wont have access to "private" anyway ...

**Comment by menski** [comment]
Ah thanks for the feedback. That was actually something I wanted to investigate which repo customers can access.

**Comment by menski** [comment]
Just a quick heads up. Please be aware that the image now contains the username and password as docker saves the command which created each layer in the metadata. So don't share this image outside of your company.

**Comment by z0rbas** [comment]
Thanks! Concerning feedback: Better open issues on your repo, or this one? Or just continue this issue?

**Comment by menski** [comment]
If it is related to the other "new" images please add the issues to the other repository. Thanks.

**Comment by menski** [comment]
It is now possible to build own enterprise images, see https://forum.camunda.org/t/new-community-docker-images/7470
