### ISSUE TITLE
wildfly-7.3.0/mysql combination not working (jboss.jdbc-driver.com_mysql_jdbc_Driver)

### ISSUE THREAD

**Issue by phax1** [camunda/docker-camunda-bpm-platform#20]
Hi,

ich think the mysql driver is not correctly installed (getting a "Services that may be the cause:" => ["jboss.jdbc-driver.com_mysql_jdbc_Driver"] )
I tried to fix myself, but was not really successful.

# running mysql and creating database
docker run --name bpmc-mysql \
  -e MYSQL_DATABASE=bpmccamunda \
  -e MYSQL_PASSWORD=camunda -e MYSQL_USER=camunda \
  -e MYSQL_ROOT_PASSWORD=camunda -d mysql:5.5

# running camunda image
docker run -d --name bpmc-camunda -p 18080:8080 -p 19990:9990 --link bpmc-mysql:db \
            -e DB_DRIVER=com.mysql.jdbc.Driver \
            -e DB_URL=jdbc:mysql://db:3306/bpmccamunda \
            -e DB_USERNAME=camunda \
            -e DB_PASSWORD=camunda \
            camunda/camunda-bpm-platform:wildfly-7.3.0

# snippet from docker logs bpmc-camunda
07:36:33,193 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) JBAS017534: Registered web context: /engine-rest
07:36:33,210 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ProcessEngine")
]) - failure description: {"JBAS014771: Services with missing/unavailable dependencies" => [
    "jboss.driver-demander.java:jboss/datasources/ProcessEngine is missing [jboss.jdbc-driver.com_mysql_jdbc_Driver]",
    "jboss.data-source.java:jboss/datasources/ProcessEngine is missing [jboss.jdbc-driver.com_mysql_jdbc_Driver]"
]}
07:36:33,225 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("add") failed - address: ([
    ("subsystem" => "camunda-bpm-platform"),
    ("process-engines" => "default")
]) - failure description: {"JBAS014879: One or more services were unable to start due to one or more indirect dependencies not being available." => {
    "Services that were unable to start:" => ["org.camunda.bpm.platform.process-engine.default"],
    "Services that may be the cause:" => ["jboss.jdbc-driver.com_mysql_jdbc_Driver"]
}}
07:36:33,236 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "camunda-example-invoice-7.3.0.war")]) - failure description: {"JBAS014879: One or more services were unable to start due to one or more indirect dependencies not being available." => {
    "Services that were unable to start:" => [
        "org.camunda.bpm.platform.process-application-module.\"camunda-example-invoice-7.3.0.war\".DEPLOY.447955d2-491f-4ee8-802c-b15c28bf45be",
        "org.camunda.bpm.platform.process-application-module.\"deployment.camunda-example-invoice-7.3.0.war:main\".START"
    ],
    "Services that may be the cause:" => ["jboss.jdbc-driver.com_mysql_jdbc_Driver"]
}}
07:36:33,274 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("add") failed - address: ([
    ("subsystem" => "datasources"),
    ("data-source" => "ProcessEngine")
]) - failure description: {
    "JBAS014771: Services with missing/unavailable dependencies" => [
        "jboss.driver-demander.java:jboss/datasources/ProcessEngine is missing [jboss.jdbc-driver.com_mysql_jdbc_Driver]",
        "jboss.data-source.java:jboss/datasources/ProcessEngine is missing [jboss.jdbc-driver.com_mysql_jdbc_Driver]"
    ],
    "JBAS014879: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => [
            "jboss.data-source.reference-factory.ProcessEngine",
            "jboss.naming.context.java.jboss.datasources.ProcessEngine"
        ],
        "Services that may be the cause:" => ["jboss.jdbc-driver.com_mysql_jdbc_Driver"]
    }
}

**Comment by menski** [comment]
Hi,

could you test your setup with the `DB_DRIVER=mysql` environment variable as described in the [README](https://github.com/camunda/docker-camunda-bpm-platform#environment-variables).

> DB_DRIVER the database driver class name (Note: use for jboss and wildfly only the database identifier h2, mysql or postgresql)

Cheers,
Sebastian

**Comment by phax1** [comment]
Thanks, 

using the DB_DRIVER=mysql (instead of tDB_DRIVER=com.mysql.jdbc.Driver) it is  working :)
I must have missed that.

Cheers,
Axel
