### ISSUE TITLE
How to get BPMN Group object?

### ISSUE THREAD

**Issue by Mrchensama** [camunda/docker-camunda-bpm-platform#204]
After searching for a while, i found that no interface supplied by camunda to get group object which is defined in Process Definition Diagram.
Is there any way to get `BPMN Group` infomation (not camunda group or user group )?
![image](https://user-images.githubusercontent.com/40376729/140015321-5777c2a6-ec9a-4dac-abdf-d4575233a69b.png)

Thanks for any reply.

**Comment by koevskinikola** [comment]
Hi @Mrchensama,

As this is a help request related to BPMN, I would recommend to open a topic on the [Camunda forum](https://forum.camunda.org/). Therefore, I am closing this issue.

Best,
Nikola
