### ISSUE TITLE
any planned support for Apple M1 Chip  linux/arm64

### ISSUE THREAD

**Issue by rmcotton** [camunda/docker-camunda-bpm-platform#205]
I tried to run up the docker image but it just froze on my Mac with M1 chip when trying to access http://localhost:8080/camunda-welcome/index.html. I noticed you dont build  arm64 distro so was wondering if this was planned and assuming this is the reason for the freezing.

```
docker run -d --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

```
```
 docker pull camunda/camunda-bpm-platform:latest --platform linux/arm64       
latest: Pulling from camunda/camunda-bpm-platform
Digest: sha256:81a8a997cd904232d3faf3d14db38d16d43cfc6f05a894a61ac3235eb6c2acbd
Status: Image is up to date for camunda/camunda-bpm-platform:latest
WARNING: image with reference camunda/camunda-bpm-platform was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
docker.io/camunda/camunda-bpm-platform:latest

```

**Comment by adampwells** [comment]
It will work if you provide the flag `--platform linux/amd64`

**Comment by adampwells** [comment]
`docker run -d --platform linux/amd64 --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest`

**Comment by aurelmegn** [comment]
> `docker run -d --platform linux/amd64 --name camunda -p 8080:8080 camunda/camunda-bpm-platform:latest`

It won't work because the container is not yet released on that platform. But this image works fine for me, https://hub.docker.com/r/dinolupo/camunda-bpm-platform.

**Comment by adampwells** [comment]
I have an M1 mac, and that is literally the command I run to fire up Camunda... I suppose it is using Rosetta under the hood, and perhaps an ARM targeted distribution will be faster

**Comment by koevskinikola** [comment]
Hi everyone,

I am closing this issue in favor of https://jira.camunda.com/browse/CAM-14301. Please follow the CAM JIRA ticket for further updates on this topic.

**Note:** We will soon disable the GitHub issues on this repository.

In the future, please use our [JIRA issue tracker](https://jira.camunda.com/projects/CAM/issues/CAM-2099?filter=allopenissues) for bug reports or feature requests.

For help requests, please open a help request topic on the [Camunda forum](https://forum.camunda.org/) or [a help request support ticket](https://docs.camunda.org/enterprise/support/#how-to-create-a-support-issue) if you are an enterprise customer.

Best,
Nikola
