### ISSUE TITLE
default username and password fail

### ISSUE THREAD

**Issue by dondragon2** [camunda/docker-camunda-bpm-platform#220]
I am having an issue when when running the Camunda image on Kubernetes and have 3 pods running based on this tutorial.
[https://camunda.com/blog/2021/08/releasing-camunda-platform-community-helm-chart/](https://camunda.com/blog/2021/08/releasing-camunda-platform-community-helm-chart/)

The containers are running without any errors and I am able to get to the lading pages and login screen. But for some reason when I enter the _**demo/demo**_ username and password it fails to login. If I scale down to 1 then it accepts it. Is there something I am missing here? what could be the problem?

There are no errors in the logs and all pods are running successfully. I am using PostgreSQL 13 running in the cluster

**Comment by ingorichtsmeier** [comment]
Hi @dondragon2,

you can either scale down the number of pods to 1 or apply this blog post: https://camunda.com/blog/2019/06/camunda-bpm-with-session-manager/

Hope this helps, Ingo

**Comment by dondragon2** [comment]
Thanks Ingo. How would this work for the spring boot version?

**Comment by ingorichtsmeier** [comment]
Hi @dondragon2,

what about this approach: https://stackoverflow.com/a/46113757

Hope this helps, Ingo

**Comment by dondragon2** [comment]
Hi @ingorichtsmeier,

What I meant was how would this work using the camunda `run-latest` docker image instead of the Tomcat or Wildfly?

Regards

**Comment by dondragon2** [comment]
thanks @ingorichtsmeier I decided to go with the tomcat version for now.

I had to do some modifications to the Dockerfile as follows.

```
FROM camunda/camunda-bpm-platform:tomcat-7.16.0

# Session Manager part
RUN wget https://repo1.maven.org/maven2/redis/clients/jedis/2.10.2/jedis-2.10.2.jar -P lib/ && \
    wget https://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager/2.3.2/memcached-session-manager-2.3.2.jar -P lib/ && \
    wget https://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc9/2.3.2/memcached-session-manager-tc9-2.3.2.jar -P lib/ && \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar -P lib/ 

RUN rm -rf lib/postgresql-42.1.0.jar

# Add Manager to context
RUN sed -i '/^<\/Context>/i \
    <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager" \
    memcachedNodes="${memcachedNodes}" \
    sticky="false" \
    sessionBackupAsync="false" \
    storageKeyPrefix="context" \
    lockingMode="auto" \
    />' conf/context.xml
```
I upgraded the Postgres library as well because of a password encryption issue

Then I modified my values.xml file for the helm install as follows
```
# Default values for camunda-bpm-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

general:
  debug: false
  replicaCount: 3

image:
  repository: <<image name that was built>>
  tag: tomcat-1.0

# By default H2 database is used, which is handy for demos and tests,
# however, H2 is not supported in a clustered scenario.
# So for real-world workloads, an external database like PostgreSQL should be used.
database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/process-engine
  credentialsSecretName: camunda-bpm-platform-db-credentials

service:
  type: ClusterIP
  port: 8080
  portName: http

metrics:
  enabled: false
  service:
    type: ClusterIP
    port: 9404
    portName: metrics
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/"
      prometheus.io/port: "9404"
# An arbitrary use of livenessProbe could make a lot of service interruption, use it wisely.
livenessProbe:
  enabled: true
  config:
    httpGet:
      path: /engine-rest/incident/count
      port: http
    initialDelaySeconds: 120
    periodSeconds: 60

readinessProbe:
  enabled: true
  config:
    httpGet:
      path: /engine-rest/incident/count
      port: http
    initialDelaySeconds: 120
    periodSeconds: 60

extraEnvs:
  - name: JAVA_OPTS
    value: -XX:-UseContainerSupport -DmemcachedNodes=redis://:Test123@redis:6379
```

**Note**: for those using a password on Redis, the password ,use be in the url preceded by a "**:**"
