### ISSUE TITLE
Trouble running the Docker image: Database does not exist

### ISSUE THREAD

**Issue by hadmut** [camunda/docker-camunda-bpm-platform#24]
Hi,

I'm just trying to run the camunda docker app, following the web page and running

docker run -d --name postgresql \
       -e POSTGRES_USER=camunda -e POSTGRES_PASSWORD=camunda \
       postgres:latest 

docker run -d --name camunda -p 8080:8080 \
       	   --link postgresql:db \
           -e DB_DRIVER=org.postgresql.Driver \
           -e DB_URL=jdbc:postgresql://db:5432/process-engine \
           -e DB_USERNAME=camunda \
           -e DB_PASSWORD=camunda \
           camunda/camunda-bpm-platform:latest

the comunda container terminates after a few seconds, and it's logs complain about 

16-Mar-2016 14:29:40.350 SEVERE [main] org.apache.tomcat.jdbc.pool.ConnectionPool.init Unable to create initial connections of pool.
 org.postgresql.util.PSQLException: FATAL: database "process-engine" does not exist

tracing the traffic confirms that camunda tries to connect to the database "process-engine", which does not exist (and is not created). 

So who should create the database if it does not exist yet?

- a postgres-container comes without a database by default. 
- the camunda-container doesn't seem to create it

And the doc page says "To skip the configuration of the database by the docker container and use ourown configuration set the environment variable SKIP_DB_CONFIG to a non empty value:", so one would expect to have the database created if _not_ setting the SKIP_DB_CONFIG.

Maybe just a documentation problem?

regards

**Comment by menski** [comment]
If you start the postgresql container without the `POSTGRES_DB` environment variable the database name will be the same as the `POSTGRES_USER` variable, so in your case `camunda`. See the [README](https://hub.docker.com/_/postgres/) of the postgresql container:

> POSTGRES_DB
> This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.

So you can either start the postgresql container with `-e POSTGRES_DB=process-engine` or the camunda container with `-e DB_URL=jdbc:postgresql://db:5432/camunda`.

**Comment by menski** [comment]
Hi @hadmut,

I will close this issue for now. Please let me know if you still have problems to run the image.

Cheers,
Sebastian
