### ISSUE TITLE
Provide image for Camunda BPM Wildfly 10 with 7.5.0-alpha4

### ISSUE THREAD

**Issue by hawky-4s-** [camunda/docker-camunda-bpm-platform#26]

**Comment by menski** [comment]
switch to wildfly 10 or provide both versions?

**Comment by hawky-4s-** [comment]
Idk. It's your pet project ;)
Always progress! Full speed ahead! 🍻

**Comment by menski** [comment]
okay so replacement it is :shipit:

**Comment by menski** [comment]
I switch the distro in the wildfly-SNAPSHOT image. So the next release will use wildfly 10 :balloon:
