### ISSUE TITLE
Reduce the size by excluding /tmp/camunda-bpm-platform.tar.gz

### ISSUE THREAD

**Issue by RasPelikan** [camunda/docker-camunda-bpm-platform#29]
Hello,

I came along at the /tmp folder inside the docker-container. I found the file  camunda-bpm-platform.tar.gz there consuming 180MB. I know that this file is used to install the wildfly but is it possible to remove it afterwards? We use a lot of containers and server-space is limited. Recuding the size would help.

Stephan

```
root@078cdf803fc5:/camunda# ll /tmp                                                                                                              
total 184372
drwxrwxrwt  3 root root      4096 Jun 16 08:07 ./
drwxr-xr-x 50 root root      4096 Jun 16 08:16 ../
-rw-------  1 root root 188780821 May 27 13:10 camunda-bpm-platform.tar.gz
drwxr-xr-x  2 root root      4096 Jun 16 08:16 hsperfdata_root/
```

**Comment by BenjaminHerbert** [comment]
You could try out by [modifying this line](https://github.com/camunda/docker-camunda-bpm-platform/blob/master/Dockerfile#L28)?
```
RUN tar xzf /tmp/camunda-bpm-platform.tar.gz -C /camunda/ server/${SERVER} --strip 2
```

to something like
```
RUN tar xzf /tmp/camunda-bpm-platform.tar.gz -C /camunda/ server/${SERVER} --strip 2 \
   && rm /tmp/camunda-bpm-platform.tar.gz
```

**Comment by menski** [comment]
This shouldn't work as the the tar is already added in line 24. A later removable will not reduce the size of the image. So the `ADD` statement in line 24 and the unpacking has to be merged into a single `RUN` command.

**Comment by BenjaminHerbert** [comment]
You're right, I missed this.
