### ISSUE TITLE
You should consider changing the project name

### ISSUE THREAD

**Issue by sdomula** [camunda/docker-camunda-bpm-platform#32]
Hi there. Just wanted to let you know about this: https://github.com/docker/docker/issues/26556

**Comment by menski** [comment]
Hi,

thanks for raising this issue. I'm aware of this topic. But currently I do not see any indication that Docker actively enforces this. If you have any additional information which shows the contrary please let me know.

However if Docker decides to enforce this, I expect that they will reach out to the maintainers before suing anyone.

Therefore I'm currently not planning to rename the repository.

Nevertheless if you have any suggestions how to rename this repository feel free to share them.

Cheers,
Sebastian
