### ISSUE TITLE
Make timezone a ENV var?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/docker-camunda-bpm-platform#33]
Possible to make the timezone a env var?

**Comment by menski** [comment]
Hi Stephen,

doesn't the [TZ variable](https://github.com/camunda/docker-camunda-bpm-platform/blob/master/README.md#change-timezone) work for you?

Cheers,
Sebastian

**Comment by StephenOTT** [comment]
Oh sorry.  Better clarification needed.  I meant make the variable set as one of the default variables so it appears in default configurations such as when using Kitematic.

Yes you can add it.  But for rapid testing, would be great if it was a default set variable.

For example in kitematic this is the default output of the env vars:
![screen shot 2016-12-01 at 2 40 47 pm](https://cloud.githubusercontent.com/assets/1994838/20809495/365341f2-b7d4-11e6-88ed-3b8f0b6faaf0.png)



Just a nice to have, it there is a elegant way to add it.

**Comment by menski** [comment]
TZ is now an environment variable
