### ISSUE TITLE
MySQL JBoss module is no longer available on GitHub

### ISSUE THREAD

**Issue by falko** [camunda/docker-camunda-bpm-platform#34]
> --2017-02-10 21:31:51--  https://raw.githubusercontent.com/camunda/camunda-bpm-platform/master/qa/wildfly-runtime/src/main/common/modules/mysql/mysql-connector-java/main/module.xml
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133, 151.101.192.133, 151.101.64.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2017-02-10 21:31:51 ERROR 404: Not Found.

This happens when [download-database-drivers.sh](https://github.com/camunda/docker-camunda-bpm-platform/blob/wildfly-SNAPSHOT/bin/download-database-drivers.sh) is executed during the build of our docker images or any derived images.

**Comment by falko** [comment]
As a workaround, I added the following to my derived `Dockerfile`:

    RUN sed -i 's/master/7.6.0/' /usr/local/bin/download-database-drivers.sh

**Comment by menski** [comment]
Hi Falko,

thanks for reporting this issue. I will fix it in the next days. I think I will just add the configuration to the repository. 

Cheers,
Sebastian

**Comment by menski** [comment]
Fixed with f01d902edc1c4ebef8dc32194fae9e156c885007 and fb4e3e5732d4a8a93751b024afdcd6995b4fdf68
