### ISSUE TITLE
Image Tags - Latest

### ISSUE THREAD

**Issue by PhilippHeuer** [camunda/docker-camunda-bpm-platform#35]
The `latest` tag should always point to the latest stable version, not to `7.7.0-alpha1`. You should add the `edge` or `experimental` tag to point at the latest alpha build so that users can stay on the latest version without worrying about bugs in the alpha.

**Comment by menski** [comment]
The idea was to always point to the latest released version of Camunda. But of course a user probably would like to use a stable version. So I would point `latest` to last minor release and create a `alpha` tag to point to latest alpha.

**Comment by menski** [comment]
The `latest` tag will from now on point to the latest stable minor release, see also https://forum.camunda.org/t/new-community-docker-images/7470
