### ISSUE TITLE
(CI) Test Task

### ISSUE THREAD

**Issue by PhilippHeuer** [camunda/docker-camunda-bpm-platform#37]
Hey,

i want to use this container as part of my CI Process in GitLab. Therefore i wrote this `feature proposal`.

I build my `.war` in GitLab and start the camunda image with the `.war`.
I would like to see a `test` parameter which i can pass to the image, which only starts and checks if the process registers without error.

It should directly quit with an error code, so that the CI Runner can handle that.
And it should quit with error code 0 if the process was registered successfully.

**Comment by menski** [comment]
Hi,

> which only starts and checks if the process registers without error.

how would you assert this?

A external script which checks the container output/state during your test phase is not matching your requirements?

**Comment by PhilippHeuer** [comment]
I would assert it just like you did in the test script using the log file. But i think that the ci script should be part for the default image. Otherwise it would require workarounds to run such tests.

Therefore i would add a script that provides e. g. `camunda-ci test example.war` from within the camunda container, which could then look like this (for a Gradle Project) in the GitLab CI Configuration:

```bash
image: java:8-jdk

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.war
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check

integration-test-76:
  image: camunda/camunda-bpm-platform:tomcat-7.6.0
  stage: test
  script:
    - camunda-ci test build/libs/example.war

integration-test-77:
  image: camunda/camunda-bpm-platform:tomcat-7.7.0
  stage: test
  script:
    - camunda-ci test build/libs/example.war
```

If you aren't against the idea, then i would create a PR to add this.

**Comment by menski** [comment]
I'm interested in this idea and would be happy about a PR.

**Comment by PhilippHeuer** [comment]
I found a better way to do this using the test library, so this is obsolete.
