### ISSUE TITLE
Alpine with open jre

### ISSUE THREAD

**Issue by prasenjithaty** [camunda/docker-camunda-bpm-platform#38]
Hi,

Any plans to release the community edition with alpine and open jre? Image sizes will considerably reduce.

Thanks.

**Comment by menski** [comment]
Hi,

actually I started to build that once, but never finished it. In general I'm in favor of having an alpine image. But didn't had time to completely build it.

**Comment by prasenjithaty** [comment]
Hi @menski,

I've built my own image with Alpine and Oracle JRE 8. I'm not a Unix guy, but tried my best and it is working with my application war. You might want to refer it and make any corrections required. Sharing it below:

```
FROM fiadliel/java8-jre

ENV VERSION 7.7.0
ENV DISTRO tomcat
ENV SERVER apache-tomcat-8.0.24
ENV LIB_DIR /camunda/lib
ENV SERVER_CONFIG /camunda/conf/server.xml
ENV NEXUS https://app.camunda.com/nexus/service/local/artifact/maven/redirect

WORKDIR /camunda

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.6/community" >> /etc/apk/repositories

RUN apk add --no-cache --virtual=build-dependencies wget ca-certificates && \
    apk add --no-cache bash xmlstarlet && \
    cd "/tmp" && \
    wget -O camunda-bpm-${DISTRO}-${VERSION}.tar.gz "${NEXUS}?r=public&g=org.camunda.bpm.${DISTRO}&a=camunda-bpm-${DISTRO}&v=${VERSION}&p=tar.gz" && \
    tar -xzf camunda-bpm-${DISTRO}-${VERSION}.tar.gz && \
    mv server/${SERVER}/* /camunda/


# add scripts
ADD bin/* /usr/local/bin/

# add database drivers
RUN /usr/local/bin/download-database-drivers.sh "${NEXUS}?r=public&g=org.camunda.bpm&a=camunda-database-settings&v=${VERSION}&p=pom"

RUN apk del build-dependencies && \
    rm -rf "/tmp/"*

EXPOSE 8080

CMD ["/usr/local/bin/configure-and-run.sh"]
```

**Comment by lightswitch05** [comment]
I've had great success with the [anapsix/alpine-java:8_jdk_unlimited](https://hub.docker.com/r/anapsix/alpine-java/) image

**Comment by prasenjithaty** [comment]
@lightswitch05 any specific reason to use jdk? Are you doing any code compilation inside your image? I wanted to create an image as small as possible with all features working. Mind sharing your Dockerfile with Camunda?

**Comment by lightswitch05** [comment]
@prasenjithaty sorry to get your hopes up, I've had great success using that docker image, but I have not tried it specifically with camunda. The same project has a JRE only version if you want to give it a try

**Comment by menski** [comment]
Hi all,

thanks for sharing. :+1:

If I find time I will look into this again. In general I would like to rewrite these images as they are currently painful to maintain with all the branches.

**Comment by prasenjithaty** [comment]
@menski did you get a chance to work on this?

**Comment by menski** [comment]
@prasenjithaty sorry no I hadn't time but maybe I get something done today

**Comment by menski** [comment]
Small update: I worked on this today on branch [single-branch](https://github.com/camunda/docker-camunda-bpm-platform/tree/single-branch). It looks quite promising from my perspective but I want to test it a little bit more, as it also heavily refactors my release process. I will be on vacation for the next two weeks so don't expect much progress in the mean time. But after that I will may merge this to master. Feel free to post any feedback or if you want to try the images you can find them under [menski/whynot](https://hub.docker.com/r/menski/whynot/tags/) (sorry for the stupid name).

**Comment by prasenjithaty** [comment]
@menski that's great news. With the latest docker release, you can even use multi-stage build to create a camunda base image. I'll try to find some time and create Dockerfile here.

**Comment by prasenjithaty** [comment]
I checked your menski/whynot image and I already see a ~33% reduction in size which is impressive. From 299MB we came down to 199MB.

**Comment by menski** [comment]
@prasenjithaty thanks for the feedback.

> use multi-stage build to create a camunda base image

Could you elaborate what your idea is behind using multi stage builds for the Camunda image? Do you want to create a java base image which is used by the tomcat/wildfly image or do you have another idea how multi-stage builds can help to optimize the image?

**Comment by prasenjithaty** [comment]
I don't actually remember what I had thought exactly at the time I commented. Please ignore.

**Comment by menski** [comment]
The new images now use alpine linux, see also https://forum.camunda.org/t/new-community-docker-images/7470
