### ISSUE TITLE
use JSON logging format for container

### ISSUE THREAD

**Issue by StephenOTT** [camunda/docker-camunda-bpm-platform#40]
Would be great if JSON format was the default format for logs. (or potentially ENV configurable).

With the way logs are captured by logging tools more frequently, having this as a core feature would be great.

**Comment by menski** [comment]
Hi Stephen,

which logging configuration do you want to configure? The Camunda engine logging configuration or the log driver of the docker container?

**Comment by menski** [comment]
Hi @StephenOTT,

thanks for clarification. Could you give me an example of the logging configuration required to produce the output you expect? Thanks.

**Comment by StephenOTT** [comment]
@menski something such as (just did a quick google search for java json loggers):

https://github.com/savoirtech/slf4j-json-logger#loggerfactory

```
{"message":"It works!","level":"INFO","thread_name":"main","class":"com.savoirtech.logging.slf4j.json.logger.BasicLoggingTests","logger_name":"com.savoirtech.logging.slf4j.json.logger.BasicLoggingTests","@timestamp":"2016-08-18 08:40:49.550-0400"}
```

**Comment by StephenOTT** [comment]
or something such as: https://stackoverflow.com/questions/29387007/does-log4j-support-json-format

**Comment by menski** [comment]
Okay I probably have to research a little bit to figure out how Camunda has to be configured to produce JSON log messages.

**Comment by StephenOTT** [comment]
@menski my research led me to the following:

https://stackoverflow.com/a/39660734

https://docs.camunda.org/manual/7.5/user-guide/logging/#slf4j

examples:
https://github.com/camunda/camunda-bpm-platform/blob/fe12354ba966df01d6634a7b534f436221f6b1d7/distro/jbossas7/subsystem/src/test/resources/log4j.properties

**Comment by StephenOTT** [comment]
This has been solved as part of: https://github.com/DigitalState/camunda-json-logging
