### ISSUE TITLE
How to migrate to another version

### ISSUE THREAD

**Issue by ilves** [camunda/docker-camunda-bpm-platform#41]
We are currently running version 7.5 but want to upgrade to version 7.7.
How should the db migration would work in this case? Is it automatic or manual? Do you have guide for this?

**Comment by menski** [comment]
Hi @ilves,

sorry for the late response. Camunda migration is a manual process, see the docs for more information about how to upgrade from [7.5 to 7.6](https://docs.camunda.org/manual/7.7/update/minor/75-to-76/) and [7.6 to 7.7](https://docs.camunda.org/manual/7.7/update/minor/76-to-77/). For the database you have to apply the patch scripts of 7.5.x, the upgrade script from 7.5 to 7.6, the patch scripts of 7.6.x and the upgrade script from 7.6 to 7.7. As this is not specific to the docker image feel free to ask more questions like this in the [Camunda forum](https://forum.camunda.org/) where more people can answer your questions.

Cheers,
Sebastian
