### ISSUE TITLE
The Camunda Rest-API is NOT accessible through: http://localhost:8080/engine-rest

### ISSUE THREAD

**Issue by ccristian** [camunda/docker-camunda-bpm-platform#44]
<h1>HTTP Status 404 - /engine-rest/</h1>
        <div class="line"></div>
        <p>
            <b>type</b> Status report
        </p>
        <p>
            <b>message</b>
            <u>/engine-rest/</u>
        </p>
        <p>
            <b>description</b>
            <u>The requested resource is not available.</u>
        </p>
        <hr class="line">
        <h3>Apache Tomcat/8.0.47</h3>

**Comment by ccristian** [comment]
Tried on different Tomcat images the url is not accessible...

**Comment by ccristian** [comment]
None of the docker images I tried do not work with engine-rest....

**Comment by menski** [comment]
Hi @ccristian,

the engine-rest artifact is deployed in all docker images. But `/engine-rest` is just the context path of the engine-rest webapp. To actually retrieve data you have to call a specific endpoint, e.g. `http://localhost:8080/engine-rest/process-definition`. For all available endpoints see the [REST API documentation](https://docs.camunda.org/manual/7.8/reference/rest/)

**Comment by ccristian** [comment]
I checked that even tried with invoice process which is deployed inside the docker image
http://localhost:8080/engine-rest/invoice ...should i try another path ?
Thanks

**Comment by ccristian** [comment]
Thanks it's ok now !!!

**Comment by pierlaz** [comment]
@ccristian Hi ccristian how do you solve it? I can't find the solution anywhere

**Comment by ephraimm** [comment]
@ccristian please could you post your fix.

**Comment by FabianTe** [comment]
@ccristian @ephraimm I'd also like to now -.-
