### ISSUE TITLE
The deploy button is not available 

### ISSUE THREAD

**Issue by ccristian** [camunda/docker-camunda-bpm-platform#45]
@menski  On the latest docker image I do not see the button Deploy in cockpit.

Is there a way to activate it ?

Thanks

**Comment by menski** [comment]
@ccristian create a deployment from cockpit is an enterprise feature (see [docs](https://docs.camunda.org/manual/7.8/webapps/cockpit/deployment-view/#create-deployment)). This docker image for the commnuity edition of Camunda and does not contain any enterprise features.

**Comment by ccristian** [comment]
I am trying to run a sample Niall did on Devoxx. Any alternative  to deploy a new process on community edition running on docker? A link would be very usefull.Thanks

**Comment by menski** [comment]
@ccristian I don't know which sample Niall used on Devoxx, but if it is only a single BPMN file you could use the REST API to [create a deployment](https://docs.camunda.org/manual/7.8/reference/rest/deployment/post-deployment/), e.g. using curl:

```
curl -v http://localhost:8080/engine-rest/deployment/create -F deployment-name="test-deployment" -F process.bpmn=@process.bpmn
```

If it is a war file with java classes etc. then you could link it while starting the docker container:

```
docker run -d --name camunda -p 8080:8080 -v /path/to/your.war:/camunda/webapps/your.war camunda/camunda-bpm-platform:latest
```
or copy it in a running container:

```
docker cp your.war camunda:/camunda/webapps/ 
```
