### ISSUE TITLE
Deployment as "ROOT" application in Tomcat. 

### ISSUE THREAD

**Issue by preston** [camunda/docker-camunda-bpm-platform#46]
Is there a configuration option for removing Tomcat's default "ROOT" application/path, and using camunda instead? I think that'd be a reasonable default behavior for the docker image since running any unrelated applications would be in other images.

**Comment by menski** [comment]
Hi @preston,

could you provide a configuration or which steps are required to configure Camunda to be the root application. Currently the image behave the same as if you would deploy the Camunda distribution without docker, i.e. unpack and run the .tar.gz from the Camunda page.

Cheers,
Sebastian

**Comment by preston** [comment]
Just replace the "ROOT" tomcat app with the Camunda one. Having the tomcat management apps in the Docker image seems pretty pointless, as people wanting to use those tools probably don't want to use Docker. :)

**Comment by gfdocquick** [comment]
@preston and @menski  you both can use a Dockerfile to do that. Example:

```Dockerfile
FROM camunda/camunda-bpm-platform:tomcat-7.13.0

WORKDIR /camunda/webapps

RUN rm ROOT/ -rf && rm h2 -rf && rm host-manager -rf && rm manager -rf && rm docs -rf && rm examples -rf && mv camunda ROOT 

WORKDIR /camunda
```
