### ISSUE TITLE
production use

### ISSUE THREAD

**Issue by JGrotex** [camunda/docker-camunda-bpm-platform#48]
Can I use this **'docker-camunda-bpm-platform'** in a production Environment as well?
Is it really recommended e.g. for multi-machine Installation?

The descriptions just mentioned _"used to demonstrate and test the Camunda BPM platform"_

thanks

**Comment by menski** [comment]
> Can I use this 'docker-camunda-bpm-platform' in a production Environment as well?

I would not recommend this personally as this image is build to work with multiple databases and application servers. I personally prefer to build minimal docker images for production use, which I control and not depend on community images. But that's your decision if you want to use a community image in production.

> Is it really recommended e.g. for multi-machine Installation?

No, where did you get that impression?
