### ISSUE TITLE
Container removes previous persistence state on restart

### ISSUE THREAD

**Issue by zlance** [camunda/docker-camunda-bpm-platform#49]
Whenever container restarts, I'm seeing that any persistence saved in the database prior to restart is cleaned out, regardless of SKIP_DB_CONFIG config flag.

Seems like the flag is only affecting server config rewrite on startup.

**Comment by menski** [comment]
Hi @zlance,

how do you start your container and what Camunda, app server and database version are you using?

**Comment by zlance** [comment]
So I start my camunda container as a simple kubernetes pod with following env flags:
        - name: DB_DRIVER
          value: org.postgresql.Driver
        - name: DB_URL
          value: jdbc:postgresql://database-url:5432/camundadb
        - name: DB_USERNAME
          value: camunda
        - name: DB_PASSWORD
          value: password
        - name: SKIP_DB_CONFIG
          value: "true"

And I'm using latest postgress RDS on AWS. It connects and works fine, but weather I got the flag or not, any time the pod restarts persistence was disappearing. I gave this pod a high level of QOS, so it doesn't get evicted by higher priority pods and also added a large amount of cpu/ram to it, so it haven't restarted, but I'm not yet 100% certain that if it does restart again it won't blow away the persistence. 

From looking at the code, it seems that Skip_DB_config can be really any non-empty string, since it's "-z" bash comparison.

**Comment by zlance** [comment]
Another question I have is moving the db to Oracle, if it works out of the box with the jdbc driver, or needs a particular oracle driver.

**Comment by menski** [comment]
I think you misunderstood the intention of the `SKIP_DB_CONFIG` variable. If it is set to anything it will not modify the database configuration of the application server on startup. The use case for that is if you want to link a own configuration file in the container which should not be modified by the start script. For example if you configuration is complex or isn't possible to achieve with the few `DB_*` variables.

From your post I assume you actually want to use the automatic configuration during start up as you specify `DB_*` variables. In combination with `SKIP_DB_CONFIG` they will have no affect and you will actually use the default settings which is a H2 file database inside the container. Which explains why it is lost if the container is recreated. So it should actually persist the data if you remove the `SKIP_DB_CONFIG` flag as the data is then actually stored in the RDS instance and not inside the container.

> Another question I have is moving the db to Oracle, if it works out of the box with the jdbc driver, or needs a particular oracle driver.

The container is not shipping a oracle driver so you would have to add it to the container first. Depending on the flavor, i.e. application server, you are using it's either simple (tomcat) or complex (wildfly). Other then that it should work.

**Comment by zlance** [comment]
@menski Thank you very much, this clears up a lot of confusion I had about this container. I'm gonna work on implementing this in my application in the next few days.
