### ISSUE TITLE
Build fails with Ubuntu 18.04 image

### ISSUE THREAD

**Issue by menski** [camunda/docker-camunda-bpm-platform#53]
The `ubuntu:latest` image was updated to 18.04 some days ago. The build now fails during package install with the following message:

```
gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
```

**Comment by WilliamEddy** [comment]
if you add this line above the first RUN statement it fixes the issue
```RUN apt-get update && apt-get install -my wget gnupg```

I would have created a branch and opened a PR, but it seems that it wont allow me to create a branch for this repository.

**Comment by menski** [comment]
The images are now based on Alpine, see https://forum.camunda.org/t/new-community-docker-images/7470
