### ISSUE TITLE
use OpenJDK or Zulu instead of Oracle JRE

### ISSUE THREAD

**Issue by kgeis** [camunda/docker-camunda-bpm-platform#54]
I'm not comfortable with using your Docker image because of questionable practice of automated acceptance of Oracle's JRE license and subsequently redistributing it. Please consider a different JRE like OpenJDK or Zulu. See:

- [Does Running Java on Docker Containers Violate Agreements?](https://www.infoq.com/news/2016/03/docker-java)
- [Running Java on Docker? You're Breaking the Law](https://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/)

**Comment by menski** [comment]
Hi,

thanks for reaching out. I was already in the process to migrate the images to openjdk. Since today Oracle jdk was dropped and replaced by openjdk. You can read more about this in this post https://forum.camunda.org/t/new-community-docker-images/7470

Cheers,
Sebastian
