### ISSUE TITLE
Get root user in Camunda Docker image

### ISSUE THREAD

**Issue by esacaceres** [camunda/docker-camunda-bpm-platform#57]
Are there any way to get root in this Camunda image?

docker pull registry.camunda.cloud/camunda-bpm-platform-ee:7.9.0

// Want to install curl and other stuff but don't have permissions
`$ apk add curl`
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
// Need superuser
`$ su root`
su: must be suid to work properly
// Need su
`$ which su`
lrwxrwxrwx    1 root     root            12 Jan  9 19:37 /bin/su -> /bin/busybox
// Need busybox-suid, but can't use apk add since don't have permissions
`$ apk --no-cache add busybox-suid`
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

Thanks.

**Comment by OtavioHenrique** [comment]
Same problem here, fortunately we had cached image on our machines, we uploaded to ECR the old image and pointed our `Dockerfile` to this image.

**Comment by menski** [comment]
Hi,

if you want to extend the docker image switch to the `root` user before installing packages etc.

```
FROM camunda/camunda-bpm-platform:latest

USER root

RUN apk --no-cache add busybox-suid

USER camunda
```

If you want to exec commands inside a running container as root use
```
docker exec -it --user root camunda bash
```

Does this answer your question?

**Comment by esacaceres** [comment]
Yes, thank you very much.
