### ISSUE TITLE
Add support for windows containers

### ISSUE THREAD

**Issue by nicojs** [camunda/docker-camunda-bpm-platform#58]
It would be awesome to have an officially supported windows container based on the [nano server](https://hub.docker.com/r/microsoft/nanoserver/) (comparable to the alpine linux base image). It would be nice if we could have a similar setup with regards to configuration.

Are windows containers something you want to officially support?

**Comment by menski** [comment]
Hi @nicojs,

why would you like to have a windows container? What use case does it solve for you, where you can't use the existing alpine container?

**Comment by nicojs** [comment]
@menski thanks for your response.

I'm working for an organization with an all Microsoft background. There is currently no knowledge of Linux or Docker other than in our own team. We're currently building and testing our software with the Camunda Alpine image and we're very happy with it. Having containers on production would be a huge win for our team, however, this is not realistic for Linux in production.

We have a lot of customers with an on-premise installation of our software. We dictate the OS requirement, but they only want to worry about Windows (that's already pretty challenging). Running docker for windows in Linux mode would be a solution, but we don't want the overhead of virtualization for all on-premise installation. Requiring our customers to upgrade to Windows server 2016 (which is the minimal requirement for native windows containers) is much more doable.

**Comment by menski** [comment]
Thanks for the explanation. But as I have no experience with Microsoft nano servers nor have an environment to develop and test such an image I'm not really able to provide such an image in the context of this project. Also as you mentioned a production use I would advise to build such an image by yourself, so you have better control over it and can tailor it to your needs. This project is a community project and the images provided are meant for development and demo purpose not real production usage. I'm happy to give you advice on how to develop such and image but as said my knowledge about the nano server environment is limited.

**Comment by KannanMaheswaran** [comment]
Hi Menski,

Are you saying, we can't use camunda docker linux image in production environment?
