### ISSUE TITLE
Server.xml and "No operations allowed after connection closed" error.

### ISSUE THREAD

**Issue by dtfuller** [camunda/docker-camunda-bpm-platform#59]
Hi everyone! 

I'm currently using the tomcat-7.7.0 image, and after having my container running for a couple of days, the system crashes with an error 500 when accessing different parts of the web user interfaces (for example, the cockpit). 

The catalina log shows a  `MySQLNonTransientConnectionException: No operations allowed after connection closed` (relevant log file: [catalina.log](https://github.com/camunda/docker-camunda-bpm-platform/files/2186509/catalina.log)), and as per [a similar case posted on the camunda forums](https://forum.camunda.org/t/process-engine-persistence-exception-no-operations-allowed-after-connection-closed/820), the solution seems to be to configure the server so that connections in the connection pool are tested before being borrowed and used. 

However, since the server.xml file contains environment variables that have already been resolved to their literal value (and injected via the docker-cli/docker-compose), setting an edited version of this file using volumes (as recommended in the README of this repo) doesn't seem to be the most appropriate solution since it would create configuration discrepancies hard to trace, down through the system's life-cycle support.

I can't believe I'm the first one to experience this. What is the correct way to approach this? Thanks in advance!

**Comment by menski** [comment]
The current approach would be to link a server.xml into the container which is configured for your environment using a connection pool. This allows you to tailor the configuration to your specific needs.

To improve the situation in the future it might be possible to add configurable connection pool settings to the image.

**Comment by dtfuller** [comment]
Thanks @menski ;)   

I ended up doing exactly that, mounting the edited `server.xml` into the image and haven't had the error appear again since.

I'm not completely satisfied with the approach, but ended up just going with it and hoping for the best - so I would agree with adding an option for a parametrization via image/container variables.
