### ISSUE TITLE
Add a spring boot based distribution

### ISSUE THREAD

**Issue by StephenOTT** [camunda/docker-camunda-bpm-platform#62]

**Comment by menski** [comment]
Hey @StephenOTT,

could you give me more details what you want to achieve here? I'm not that familiar with spring boot but isn't a Camunda spring boot deployment your process application bundle with the Camunda Spring Boot Starter in a single jar file? So you basically just need a container to run Java?

**Comment by ingorichtsmeier** [comment]
Hi @StephenOTT, a dockerfile for Spring-Boot is normally:
```
FROM some-java-image
COPY my.jar into the image
RUN java -jar myjar
```
All configuration can be done by command line arguments or environment variables by your need as it is supposed by spring-boot: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html.

I think a short example is more useful than a prebuild spring-boot distribution.

**Comment by falko** [comment]
related to: https://app.camunda.com/jira/browse/CAM-10062

**Comment by ceefour** [comment]
We're using Camunda BPM Run `run-7.13.0-alpha4` on Kubernetes now:
https://blog.camunda.com/post/2020/03/introducing-camunda-bpm-run/

Hopefully all goes well :)

cc @tmetzke

**Comment by StephenOTT** [comment]
Ya think we can close this issue.  As Camunda Run is exactly this ask.
