### ISSUE TITLE
Variable DB_URL doesn't seem to work?

### ISSUE THREAD

**Issue by mitchhanks** [camunda/docker-camunda-bpm-platform#66]
When attempting to connect the docker image to a MySQL database it seems to be trying to connect to my local IP address?

 java.sql.SQLException: Access denied for user 'root'@'host86-175-241-246.range86-175.btcentralplus.com' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4074)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4006)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919)

My run command:

docker run -d --name camunda -p 8080:8080 --link mysql \
 -e DB_DRIVER=com.mysql.jdbc.Driver \
 -e DB_URL="jdbc:mysql://icemain.hopto.org:3306/process-engine" \
 -e DB_USERNAME="root" \
 -e DB_PASSWORD="pass" \
 -e WAIT_FOR= camunda/camunda-bpm-platform:latest

**Comment by menski** [comment]
> Access denied for user 'root'@'host86-175-241-246.range86-175.btcentralplus.com'

Means MySQL denied a connection from user `root` from host `host86-175-241-246.range86-175.btcentralplus.com`. It is not the URL it connects to, but your identifier.

Make sure you configured the MySQL to allow remote access for the root user.

**Comment by mitchhanks** [comment]
> > Access denied for user 'root'@'host86-175-241-246.range86-175.btcentralplus.com'
> 
> Means MySQL denied a connection from user `root` from host `host86-175-241-246.range86-175.btcentralplus.com`. It is not the URL it connects to, but your identifier.
> 
> Make sure you configured the MySQL to allow remote access for the root user.

Thank you I have resolved it. My environment variable for the password contained a ! so I put a backslash before it as I thought it would just escape it, however I was wrong. I solved it by putting my password variable in single quotes.
