### ISSUE TITLE
Add support for SA_PASSWORD_FILE for Docker Swarm

### ISSUE THREAD

**Issue by pme123** [camunda/docker-camunda-bpm-platform#68]
it would be nice to have possibility to set DB_PASSWORD by setting Docker secret and passing it into DB_PASSWORD_FILE env variable.

Analog:
https://github.com/Microsoft/mssql-docker/issues/326

**Comment by menski** [comment]
If I understand your use case correctly you want to specify a file path which contains the database password. During startup the container should then read the password from the file correct?

Are you interested to provide a pull request for this feature?

**Comment by AndreaGiardini** [comment]
This has been fixed :) The env variable `DB_PASSWORD_FILE` is now available
