### ISSUE TITLE
invalid option when executing docker run

### ISSUE THREAD

**Issue by waterskier2007** [camunda/docker-camunda-bpm-platform#76]
after building a docker image (using enterprise edition configuration, not sure if this applies to non-EE builds) I receive the error ": invalid option" when executing docker run <image-name>

This is on docker for windows, using linux containers

![image](https://user-images.githubusercontent.com/2089840/49388776-c1476400-f6f2-11e8-9706-a47ca3030db2.png)

**Comment by waterskier2007** [comment]
I am looking into this more, but I also need to include than on windows, the download.sh file needs to be change to use LF line endings vs CRLF or the docker build will fail. Not sure if this contributes to the issue down the line.

**Comment by waterskier2007** [comment]
So, this is related to the core.autocrlf option in git. It was a user error this time, but someone wiser than I might be able to determine if this can be addressed.

**Comment by menski** [comment]
@waterskier2007 what was your configuration for `core.autocrlf` and what was the fix?

**Comment by waterskier2007** [comment]
@menski I had autocrlf set to true, and the fix was either to turn it off before cloning, or to manually change the download.sh line endings from CRLF to LF before running the build
