### ISSUE TITLE
Dead twitter demo link in README

### ISSUE THREAD

**Issue by marcfreiheit** [camunda/docker-camunda-bpm-platform#79]
Hey guys,

just realized that your [twitter demo](
https://github.com/camunda/camunda-consulting/tree/master/showcases/twitter) link from your README.md is dead.

Best regards!

**Comment by menski** [comment]
Thanks for reporting, probably cause by this commit https://github.com/camunda-consulting/code/commit/e760903049d9c9326798b5c7aa3bac1799c693ac

It should now link to https://github.com/camunda-consulting/code/tree/master/one-time-examples/twitter
