### ISSUE TITLE
Add sensible default config for Postgres

### ISSUE THREAD

**Issue by AndreaGiardini** [camunda/docker-camunda-bpm-platform#80]
Every time I use the tomcat image with postgres database I find myself repeating the following settings in my Dockerfile:

```
    xmlstarlet ed -O --inplace \
    --insert "//Resource[@name='jdbc/ProcessEngine']" --type attr \
    -n testOnBorrow -v true \
    --insert "//Resource[@name='jdbc/ProcessEngine']" --type attr \
    -n validationQuery -v "SELECT 1" /camunda/conf/server.xml && \
    xmlstarlet ed -O --inplace \
    -N 'N=http://www.camunda.org/schema/1.0/BpmPlatform' -s '//N:properties' \
    -t elem -n property -v "false" /camunda/conf/bpm-platform.xml && \
    xmlstarlet ed -O --inplace \
    -N 'N=http://www.camunda.org/schema/1.0/BpmPlatform' -i '//N:property[not(@name)]' \
    -t 'attr' -n 'name' -v 'jdbcBatchProcessing' /camunda/conf/bpm-platform.xml
```

I am asking myself if it makes sense to add these settings by default every time the postgresql driver is selected.

Would be nice to have @menski 's opinion about it

**Comment by falko** [comment]
@AndreaGiardini the docs do not mention issues with JDBC batching on PostgreSQL: https://docs.camunda.org/manual/latest/user-guide/process-engine/database/#jdbc-batch-processing

Did you experience issues with PostgreSQL yourself?

**Comment by AndreaGiardini** [comment]
This has been fixed
