### ISSUE TITLE
Deploy BPMN without REST API call

### ISSUE THREAD

**Issue by milankaku** [camunda/docker-camunda-bpm-platform#82]
Is there a way to deploy the BPMN without using the REST API call? I realized that if the camunda server ever comes down, when the server comes back up, the BPMN's I have deployed are gone since the server reset.

I am not using Spring Boot/Java, and the camunda server is deployed on an EC2 using a Dockerfile. Is there a way I can add my xml files directly to the camunda server from the Dockerfile to a certain directory? Is the REST API the only way? Do you see another way to handle this issue?

Any help would be appreciated @menski !

**Comment by AndreaGiardini** [comment]
Hello @milankaku 

I will close this issue since it's a support request rather than a problem with our docker image. You are free to ask for help in our community forum at forum.camunda.org :)
