### ISSUE TITLE
Artifact download error - Docker build

### ISSUE THREAD

**Issue by oliveiradouglas** [camunda/docker-camunda-bpm-platform#84]
Hello, 
I am having problem when try build the docker image:

![image](https://user-images.githubusercontent.com/11797503/55327776-3a688500-5461-11e9-89c7-ac0150959da6.png)

Seems that the nexus url for artifact has changed, some idea?

**Comment by menski** [comment]
Hi @oliveiradouglas,

yes the Camunda Nexus was migrated to version 3 which does not support this way of download anymore. We fixed this by this commit https://github.com/camunda/docker-camunda-bpm-platform/commit/34176ef29aabc0f97cdfc14d5e4c5840705894ad.
