### ISSUE TITLE
Error building customized image

### ISSUE THREAD

**Issue by maartenflippo** [camunda/docker-camunda-bpm-platform#86]
I need a docker image with camunda 7.8.0 on wildfly, and since that release does not exist on docker hub, I attempted to build the image myself as stated in the README. However, when I execute the command in an unmodified clone of this repository, I get the following error.

```
$ docker build -t camunda-bpm-platform --build-arg DISTRO=wildfly --build-arg VERSION=7.8.0 .

Sending build context to Docker daemon  262.1kB
Step 1/34 : FROM openjdk:8u191-jre-alpine3.9 as builder
 ---> b76bbdb2809f
Step 2/34 : ARG VERSION=7.10.0
 ---> Using cache
 ---> 3183ad309006
Step 3/34 : ARG DISTRO=tomcat
 ---> Using cache
 ---> a8d2d9b1dce3
Step 4/34 : ARG SNAPSHOT=false
 ---> Using cache
 ---> 0e8357ff4037
Step 5/34 : ARG EE=false
 ---> Using cache
 ---> acf04ba432f0
Step 6/34 : ARG USER
 ---> Using cache
 ---> 6c8daeff522e
Step 7/34 : ARG PASSWORD
 ---> Using cache
 ---> 007fac60d4c8
Step 8/34 : RUN apk add --no-cache         ca-certificates         maven         tar         wget         xmlstarlet
 ---> Using cache
 ---> d6b58de2d1a5
Step 9/34 : COPY settings.xml download.sh camunda-tomcat.sh camunda-wildfly.sh  /tmp/
 ---> Using cache
 ---> 021064b518a4
Step 10/34 : RUN /tmp/download.sh
 ---> Running in 81a3d98b0ff3
/bin/sh: illegal option -
The command '/bin/sh -c /tmp/download.sh' returned a non-zero code: 2
```

I am on Windows.

**Comment by menski** [comment]
Hi @maartenflippo,

seems to be related to the Windows line endings. See https://github.com/camunda/docker-camunda-bpm-platform/issues/76#issuecomment-446174924 and https://github.com/camunda/docker-camunda-bpm-platform/issues/60#issuecomment-415156077 for possible workarounds.

Feel free to reopen the issue if the problem persists.

**Comment by menski** [comment]
Btw `camunda/camunda-bpm-platform:wildfly10-7.8.0` exists on docker hub
