### ISSUE TITLE
Run Camunda in Docker with MS SQL as Database Host

### ISSUE THREAD

**Issue by DrunkenHusky** [camunda/docker-camunda-bpm-platform#87]
Hi, 
We would like to run Camunda in Docker with an external MS SQL Database. How can we ship these variables during the provisioning? At the end, we need to define these Values during the pull:

- DATABASESERVER
- APPLICATIONNAME
- DOMAIN\USERNAME
- DRIVER (MSSQL) --> Actually you do not include that in the description?
- INTEGRATED SECURITYfor the Connection String

Any ideas, how we can achieve that?

An example, how our file under \conf\server.xml should look like:

`<Resource name="jdbc/ProcessEngine"
    auth="Container"
    type="javax.sql.DataSource"
    factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
    uniqueResourceName="process-engine"
    driverClassName="com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url="jdbc:sqlserver://DATABASESERVER;databaseName=Camunda;integratedSecurity=true;applicationName=APPLICATIONNAME;"
    defaultTransactionIsolation="READ_COMMITTED"
    username="DOMAIN\USERNAME"
    password=""
    maxActive="20"
    minIdle="5" />`

Thanks!

**Comment by menski** [comment]
Hi @DrunkenHusky,

did you already check if you can provide all these settings using the database environment variables (https://github.com/camunda/docker-camunda-bpm-platform#database-environment-variables). These environment variables are used to modify the server.xml on startup, i.e. see https://github.com/camunda/docker-camunda-bpm-platform/blob/34176ef29aabc0f97cdfc14d5e4c5840705894ad/camunda-tomcat.sh#L14-L22.

 If not you can still add a custom server.xml to the image by either mounting it as a volume or extending the existing image.

> DRIVER (MSSQL) --> Actually you do not include that in the description?

The image does not ship with a MSSQL driver included for licensing reasons. You can add the driver jar again either as volume mount or by extending the existing image.

**Comment by DrunkenHusky** [comment]
hi @menski 
Thank you for your feedback. I will try to use your trick with the enviroment variables, thanks! I will mark this as "solved", as in my understanding this is nothing you can/will support as there is a licensing issue with the driver. But I will try to get this up and running by myself.
